/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* enable custom memory manager */
#define ASN1_ALLOCATOR 

/* enable AVN support */
#define ASN1_HAS_IOSTREAM 

/* disable multithreading for boost/pool */
#define BOOST_NO_MT 

/* Define to 1 if you have the <inttypes.h> header file. */
/* #undef HAVE_INTTYPES_H */

/* Define to 1 if you have the <memory.h> header file. */
/* #undef HAVE_MEMORY_H */

/* define if the compiler implements namespaces */
#define HAVE_NAMESPACES 

/* define if the compiler has ASNI compliant iostream */
#define HAVE_NEW_IOSTREAM 

/* Define if you have POSIX threads libraries and header files. */
/* #undef HAVE_PTHREAD */

/* Define to 1 if you have the <stdint.h> header file. */
/* #undef HAVE_STDINT_H */

/* Define to 1 if you have the <stdlib.h> header file. */
/* #undef HAVE_STDLIB_H */

/* define if the compiler supports Standard Template Library */
#define HAVE_STL 

/* Define to 1 if you have the <strings.h> header file. */
/* #undef HAVE_STRINGS_H */

/* Define to 1 if you have the <string.h> header file. */
/* #undef HAVE_STRING_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
/* #undef HAVE_SYS_STAT_H */

/* Define to 1 if you have the <sys/types.h> header file. */
/* #undef HAVE_SYS_TYPES_H */

/* Define to 1 if you have the <unistd.h> header file. */
/* #undef HAVE_UNISTD_H */

/* define if the compiler has wstring */
#define HAVE_WSTRING 

/* define if explicit wstring typedef is needed */
/* #undef NEED_WSTRING_TYPEDEF */

/* Name of package */
#define PACKAGE "iiiasn1"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define to the necessary symbol if this constant uses a non-standard name on
   your system. */
/* #undef PTHREAD_CREATE_JOINABLE */

/* Define to 1 if you have the ANSI C header files. */
/* #undef STDC_HEADERS */

/* Version number of package */
#define VERSION "2_12"

/* define if the GLIB need the flag to turn on wstring support */
/* #undef _GLIBCPP_USE_WCHAR_T */

/* enable STLport thread support */
/* #undef _REENTRANT */

/* enable libstdc++ pthread support */
/* #undef __STL_PTHREADS */

/* enable libstdc++ WIN32 thread support */
/* #undef __STL_WIN32THREADS */

/* throw std::bad_alloc when memory is exhausted */
#define __THROW_BAD_ALLOC 
